// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class ActivityLog
{
    public int ActivityLogId { get; set; }

    public int CreatedById { get; set; }

    public int CreatedId { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }
}