// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class AttendanceLog
{
    public int AttendanceLogId { get; set; }

    public int? UserId { get; set; }

    public int? EmployeeId { get; set; }

    public string AttendanceInLat { get; set; }

    public string AttendanceInLon { get; set; }

    public DateTime? TimeInAt { get; set; }

    public string TimeInLocationName { get; set; }

    public string AttendanceOutLat { get; set; }

    public string AttendanceOutLon { get; set; }

    public DateTime? TimeOutAt { get; set; }

    public string TimeOutLocationName { get; set; }

    public int AttendanceStatusId { get; set; }

    public string TimeInBy { get; set; }

    public string TimeOutBy { get; set; }

    public string TimeInType { get; set; }

    public string TimeOutType { get; set; }

    public DateTime? TimeInMobile { get; set; }

    public DateTime? TimeOutMobile { get; set; }

    public DateTime? TimeInImage { get; set; }

    public DateTime? TimeOutImage { get; set; }

    public string AttendanceInImagePath { get; set; }

    public string AttendanceOutImagePath { get; set; }

    public virtual AttendanceStatus AttendanceStatus { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual User User { get; set; }
}