// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class AttendanceStatus
{
    public int AttendanceStatusId { get; set; }

    public string Status { get; set; }

    public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; } = new List<AttendanceLog>();
}