// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class Department
{
    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? ParentDepartmentId { get; set; }

    public int? BranchId { get; set; }

    public bool IsActive { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<EmpUserBrDeptMapping> EmpUserBrDeptMappings { get; set; } = new List<EmpUserBrDeptMapping>();

    public virtual ICollection<Department> InverseParentDepartment { get; set; } = new List<Department>();

    public virtual Department ParentDepartment { get; set; }
}