// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class DeviceSession
{
    public int DeviceSessionId { get; set; }

    public string DeviceId { get; set; }

    public string DeviceName { get; set; }

    public string DevicePlatform { get; set; }

    public int? UserId { get; set; }

    public int? EmployeeId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual User User { get; set; }
}