// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public int RoleId { get; set; }

    public string EmployeeEmail { get; set; }

    public string EmployeePassword { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public string EmployeeCode { get; set; }

    public string EmployeeFatherName { get; set; }

    public string Cnic { get; set; }

    public string JobTitle { get; set; }

    public string MobileNumber { get; set; }

    public int? PaymentTypeId { get; set; }

    public int? ShiftTypeId { get; set; }

    public int? EmployeeTypeId { get; set; }

    public string EmergencyContact { get; set; }

    public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; } = new List<AttendanceLog>();

    public virtual ICollection<DeviceSession> DeviceSessions { get; set; } = new List<DeviceSession>();

    public virtual ICollection<EmpUserBrDeptMapping> EmpUserBrDeptMappings { get; set; } = new List<EmpUserBrDeptMapping>();

    public virtual ICollection<EmployeeFile> EmployeeFiles { get; set; } = new List<EmployeeFile>();

    public virtual EmployeeType EmployeeType { get; set; }

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    public virtual PaymentType PaymentType { get; set; }

    public virtual Role Role { get; set; }

    public virtual ShiftType ShiftType { get; set; }
}