// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class EmployeeCodeLog
{
    public int EmployeeCodeLogId { get; set; }

    public string EmployeeCode { get; set; }

    public int CodeNumber { get; set; }

    public DateTime CreatedAt { get; set; }

    public int EmployeeId { get; set; }
}