// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class EmployeeFile
{
    public int EmployeeFileId { get; set; }

    public int EmployeeId { get; set; }

    public string FilePath { get; set; }

    public string Extension { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual Employee Employee { get; set; }
}