// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class EmpUserDepartmentMapping
{
    public int DepartmentMappingId { get; set; }

    public int? EmployeeId { get; set; }

    public int DepartmentId { get; set; }

    public int? UserId { get; set; }

    public virtual Department Department { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual User User { get; set; }
}