// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class Location
{
    public int LocationId { get; set; }

    public string Latitude { get; set; }

    public string Longitude { get; set; }

    public string LocationName { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? EmployeeId { get; set; }

    public int? UserId { get; set; }

    public int Radius { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual User User { get; set; }
}