// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class PaymentType
{
    public int PaymentTypeId { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}