// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PPFAttendanceApi.Models;

public partial class ppfdbContext : DbContext
{
    public ppfdbContext(DbContextOptions<ppfdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActivityLog> ActivityLogs { get; set; }

    public virtual DbSet<AttendanceLog> AttendanceLogs { get; set; }

    public virtual DbSet<AttendanceStatus> AttendanceStatuses { get; set; }

    public virtual DbSet<Branch> Branches { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<DeviceSession> DeviceSessions { get; set; }

    public virtual DbSet<EmpUserBrDeptMapping> EmpUserBrDeptMappings { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeFile> EmployeeFiles { get; set; }

    public virtual DbSet<EmployeeType> EmployeeTypes { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<PaymentType> PaymentTypes { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ShiftType> ShiftTypes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserFile> UserFiles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ActivityLog>(entity =>
        {
            entity.HasKey(e => e.ActivityLogId).HasName("activity_log_pkey");

            entity.ToTable("activity_log", "logs");

            entity.HasIndex(e => e.CreatedAt, "idx_activity_log_created_at").IsDescending();

            entity.HasIndex(e => e.CreatedById, "idx_activity_log_created_by_id");

            entity.HasIndex(e => e.CreatedId, "idx_activity_log_created_id");

            entity.Property(e => e.ActivityLogId).HasColumnName("activity_log_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedById).HasColumnName("created_by_id");
            entity.Property(e => e.CreatedId).HasColumnName("created_id");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("description");
        });

        modelBuilder.Entity<AttendanceLog>(entity =>
        {
            entity.HasKey(e => e.AttendanceLogId).HasName("attendance_log_pkey");

            entity.ToTable("attendance_log", "logs");

            entity.HasIndex(e => e.AttendanceStatusId, "idx_attendance_log_attendance_status_id");

            entity.HasIndex(e => new { e.EmployeeId, e.TimeInAt }, "idx_attendance_log_complete_records")
                .IsDescending(false, true)
                .HasFilter("(time_out_at IS NOT NULL)");

            entity.HasIndex(e => e.EmployeeId, "idx_attendance_log_employee_id");

            entity.HasIndex(e => new { e.EmployeeId, e.AttendanceStatusId }, "idx_attendance_log_employee_status");

            entity.HasIndex(e => new { e.EmployeeId, e.TimeInAt }, "idx_attendance_log_employee_time_in").IsDescending(false, true);

            entity.HasIndex(e => e.TimeInAt, "idx_attendance_log_time_in_at");

            entity.HasIndex(e => e.TimeInLocationName, "idx_attendance_log_time_in_location_type");

            entity.HasIndex(e => e.TimeOutAt, "idx_attendance_log_time_out_at");

            entity.HasIndex(e => e.TimeOutLocationName, "idx_attendance_log_time_out_location_type");

            entity.HasIndex(e => e.UserId, "idx_attendance_log_user_id");

            entity.Property(e => e.AttendanceLogId).HasColumnName("attendance_log_id");
            entity.Property(e => e.AttendanceDate).HasColumnName("attendance_date");
            entity.Property(e => e.AttendanceInImagePath)
                .HasColumnType("character varying")
                .HasColumnName("attendance_in_image_path");
            entity.Property(e => e.AttendanceInLat)
                .HasColumnType("character varying")
                .HasColumnName("attendance_in_lat");
            entity.Property(e => e.AttendanceInLon)
                .HasColumnType("character varying")
                .HasColumnName("attendance_in_lon");
            entity.Property(e => e.AttendanceOutImagePath)
                .HasColumnType("character varying")
                .HasColumnName("attendance_out_image_path");
            entity.Property(e => e.AttendanceOutLat)
                .HasColumnType("character varying")
                .HasColumnName("attendance_out_lat");
            entity.Property(e => e.AttendanceOutLon)
                .HasColumnType("character varying")
                .HasColumnName("attendance_out_lon");
            entity.Property(e => e.AttendanceStatusId).HasColumnName("attendance_status_id");
            entity.Property(e => e.EmployeeId).HasColumnName("employee_id");
            entity.Property(e => e.TimeInAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("time_in_at");
            entity.Property(e => e.TimeInBy)
                .HasColumnType("character varying")
                .HasColumnName("time_in_by");
            entity.Property(e => e.TimeInImage)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("time_in_image");
            entity.Property(e => e.TimeInLocationName)
                .HasColumnType("character varying")
                .HasColumnName("time_in_location_name");
            entity.Property(e => e.TimeInMobile)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("time_in_mobile");
            entity.Property(e => e.TimeInType)
                .HasColumnType("character varying")
                .HasColumnName("time_in_type");
            entity.Property(e => e.TimeOutAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("time_out_at");
            entity.Property(e => e.TimeOutBy)
                .HasColumnType("character varying")
                .HasColumnName("time_out_by");
            entity.Property(e => e.TimeOutImage)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("time_out_image");
            entity.Property(e => e.TimeOutLocationName)
                .HasColumnType("character varying")
                .HasColumnName("time_out_location_name");
            entity.Property(e => e.TimeOutMobile)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("time_out_mobile");
            entity.Property(e => e.TimeOutType)
                .HasColumnType("character varying")
                .HasColumnName("time_out_type");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.AttendanceStatus).WithMany(p => p.AttendanceLogs)
                .HasForeignKey(d => d.AttendanceStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("attendance_status_key");

            entity.HasOne(d => d.Employee).WithMany(p => p.AttendanceLogs)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("attendance_employee_key");

            entity.HasOne(d => d.User).WithMany(p => p.AttendanceLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("attendance_user_key");
        });

        modelBuilder.Entity<AttendanceStatus>(entity =>
        {
            entity.HasKey(e => e.AttendanceStatusId).HasName("attendance_status_pkey");

            entity.ToTable("attendance_status", "utils");

            entity.HasIndex(e => e.Status, "idx_attendance_status_status");

            entity.Property(e => e.AttendanceStatusId).HasColumnName("attendance_status_id");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("status");
        });

        modelBuilder.Entity<Branch>(entity =>
        {
            entity.HasKey(e => e.BranchId).HasName("branch_pkey");

            entity.ToTable("branch", "master");

            entity.Property(e => e.BranchId).HasColumnName("branch_id");
            entity.Property(e => e.BranchName)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("branch_name");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Latitude)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("latitude");
            entity.Property(e => e.Longitude)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("longitude");
            entity.Property(e => e.Radius).HasColumnName("radius");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Branches)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("branch_user_key");
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.DepartmentId).HasName("department_pkey");

            entity.ToTable("department", "master");

            entity.Property(e => e.DepartmentId).HasColumnName("department_id");
            entity.Property(e => e.BranchId).HasColumnName("branch_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.CreatedBy).HasColumnName("created_by");
            entity.Property(e => e.DepartmentName)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("department_name");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.ParentDepartmentId).HasColumnName("parent_department_id");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Branch).WithMany(p => p.Departments)
                .HasForeignKey(d => d.BranchId)
                .HasConstraintName("department_branch_key");

            entity.HasOne(d => d.ParentDepartment).WithMany(p => p.InverseParentDepartment)
                .HasForeignKey(d => d.ParentDepartmentId)
                .HasConstraintName("department_subDepartment_key");
        });

        modelBuilder.Entity<DeviceSession>(entity =>
        {
            entity.HasKey(e => e.DeviceSessionId).HasName("device_session_pkey");

            entity.ToTable("device_session", "logs");

            entity.Property(e => e.DeviceSessionId)
                .HasDefaultValueSql("nextval('logs.user_session_user_session_id_seq'::regclass)")
                .HasColumnName("device_session_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.DeviceId)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("device_id");
            entity.Property(e => e.DeviceName)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("device_name");
            entity.Property(e => e.DevicePlatform)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("device_platform");
            entity.Property(e => e.EmployeeId).HasColumnName("employee_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Employee).WithMany(p => p.DeviceSessions)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("userSession_employee_key");

            entity.HasOne(d => d.User).WithMany(p => p.DeviceSessions)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("userSession_manager_key");
        });

        modelBuilder.Entity<EmpUserBrDeptMapping>(entity =>
        {
            entity.HasKey(e => e.BrDeptMappingId).HasName("br_dept_mapping_pkey");

            entity.ToTable("emp_user_br_dept_mapping", "master");

            entity.Property(e => e.BrDeptMappingId)
                .HasDefaultValueSql("nextval('master.employee_department_mapping_employee_department_mapping_id_seq'::regclass)")
                .HasColumnName("br_dept_mapping_id");
            entity.Property(e => e.BranchId).HasColumnName("branch_id");
            entity.Property(e => e.DepartmentId).HasColumnName("department_id");
            entity.Property(e => e.EmployeeId).HasColumnName("employee_id");
            entity.Property(e => e.IsPrimaryBranch).HasColumnName("is_primary_branch");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Branch).WithMany(p => p.EmpUserBrDeptMappings)
                .HasForeignKey(d => d.BranchId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("mapping_branch_key");

            entity.HasOne(d => d.Department).WithMany(p => p.EmpUserBrDeptMappings)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("mapping_department_key");

            entity.HasOne(d => d.Employee).WithMany(p => p.EmpUserBrDeptMappings)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("mapping_employee_key");

            entity.HasOne(d => d.User).WithMany(p => p.EmpUserBrDeptMappings)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("mapping_user_key");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("employees_pkey");

            entity.ToTable("employees", "master");

            entity.HasIndex(e => new { e.IsActive, e.RoleId }, "idx_employees_active_role");

            entity.HasIndex(e => e.EmployeeId, "idx_employees_employee_id");

            entity.HasIndex(e => e.IsActive, "idx_employees_is_active");

            entity.HasIndex(e => e.RoleId, "idx_employees_role_id");

            entity.Property(e => e.EmployeeId).HasColumnName("employee_id");
            entity.Property(e => e.Cnic)
                .HasColumnType("character varying")
                .HasColumnName("cnic");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.EmergencyContact)
                .HasColumnType("character varying")
                .HasColumnName("emergency_contact");
            entity.Property(e => e.EmployeeCode)
                .HasColumnType("character varying")
                .HasColumnName("employee_code");
            entity.Property(e => e.EmployeeEmail)
                .HasColumnType("character varying")
                .HasColumnName("employee_email");
            entity.Property(e => e.EmployeeFatherName)
                .HasColumnType("character varying")
                .HasColumnName("employee_father_name");
            entity.Property(e => e.EmployeeName)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("employee_name");
            entity.Property(e => e.EmployeePassword)
                .HasColumnType("character varying")
                .HasColumnName("employee_password");
            entity.Property(e => e.EmployeeTypeId).HasColumnName("employee_type_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.JobTitle)
                .HasColumnType("character varying")
                .HasColumnName("job_title");
            entity.Property(e => e.MobileNumber)
                .HasColumnType("character varying")
                .HasColumnName("mobile_number");
            entity.Property(e => e.PaymentTypeId).HasColumnName("payment_type_id");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.ShiftTypeId).HasColumnName("shift_type_id");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.EmployeeType).WithMany(p => p.Employees)
                .HasForeignKey(d => d.EmployeeTypeId)
                .HasConstraintName("employee_employeeType_key");

            entity.HasOne(d => d.PaymentType).WithMany(p => p.Employees)
                .HasForeignKey(d => d.PaymentTypeId)
                .HasConstraintName("employee_payment_key");

            entity.HasOne(d => d.Role).WithMany(p => p.Employees)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("employee_role_key");

            entity.HasOne(d => d.ShiftType).WithMany(p => p.Employees)
                .HasForeignKey(d => d.ShiftTypeId)
                .HasConstraintName("employee_shiftType_key");
        });

        modelBuilder.Entity<EmployeeFile>(entity =>
        {
            entity.HasKey(e => e.EmployeeFileId).HasName("employee_file_pkey");

            entity.ToTable("employee_file", "media");

            entity.HasIndex(e => new { e.EmployeeId, e.CreatedAt }, "idx_employee_file_employee_created").IsDescending(false, true);

            entity.HasIndex(e => e.EmployeeId, "idx_employee_file_employee_id");

            entity.Property(e => e.EmployeeFileId).HasColumnName("employee_file_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.EmployeeId).HasColumnName("employee_id");
            entity.Property(e => e.Extension)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("extension");
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("file_path");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Employee).WithMany(p => p.EmployeeFiles)
                .HasForeignKey(d => d.EmployeeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("employeeFile_employee_key");
        });

        modelBuilder.Entity<EmployeeType>(entity =>
        {
            entity.HasKey(e => e.EmployeeTypeId).HasName("employee_type_pkey");

            entity.ToTable("employee_type", "utils");

            entity.Property(e => e.EmployeeTypeId).HasColumnName("employee_type_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("type");
        });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("locations_pkey");

            entity.ToTable("locations");

            entity.HasIndex(e => e.EmployeeId, "idx_locations_employee_id");

            entity.HasIndex(e => new { e.EmployeeId, e.LocationName }, "idx_locations_employee_type");

            entity.HasIndex(e => e.LocationName, "idx_locations_location_type");

            entity.HasIndex(e => e.UserId, "idx_locations_user_id");

            entity.HasIndex(e => new { e.UserId, e.LocationName }, "idx_locations_user_type");

            entity.Property(e => e.LocationId).HasColumnName("location_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.EmployeeId).HasColumnName("employee_id");
            entity.Property(e => e.Latitude)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("latitude");
            entity.Property(e => e.LocationName)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("location_name");
            entity.Property(e => e.Longitude)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("longitude");
            entity.Property(e => e.Radius).HasColumnName("radius");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.Employee).WithMany(p => p.Locations)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("location_employee_key");

            entity.HasOne(d => d.User).WithMany(p => p.Locations)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("location_user_key");
        });

        modelBuilder.Entity<PaymentType>(entity =>
        {
            entity.HasKey(e => e.PaymentTypeId).HasName("payment_type_pkey");

            entity.ToTable("payment_type", "utils");

            entity.Property(e => e.PaymentTypeId).HasColumnName("payment_type_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("type");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("role_pkey");

            entity.ToTable("role", "master");

            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("role_name");
        });

        modelBuilder.Entity<ShiftType>(entity =>
        {
            entity.HasKey(e => e.ShiftTypeId).HasName("shift_type_pkey");

            entity.ToTable("shift_type", "utils");

            entity.Property(e => e.ShiftTypeId).HasColumnName("shift_type_id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.ShiftEndAt).HasColumnName("shift_end_at");
            entity.Property(e => e.ShiftHours).HasColumnName("shift_hours");
            entity.Property(e => e.ShiftStartAt).HasColumnName("shift_start_at");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("type");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("user_pkey");

            entity.ToTable("user", "master");

            entity.HasIndex(e => e.IsActive, "idx_user_is_active");

            entity.HasIndex(e => e.RoleId, "idx_user_role_id");

            entity.HasIndex(e => e.UserId, "idx_user_user_id");

            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("is_active");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserEmail)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("user_email");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("user_name");
            entity.Property(e => e.UserPassword)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("user_password");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("user_role_key");
        });

        modelBuilder.Entity<UserFile>(entity =>
        {
            entity.HasKey(e => e.UserFileId).HasName("user_file_pkey");

            entity.ToTable("user_file", "media");

            entity.HasIndex(e => new { e.UserId, e.CreatedAt }, "idx_user_file_user_created").IsDescending(false, true);

            entity.HasIndex(e => e.UserId, "idx_user_file_user_id");

            entity.Property(e => e.UserFileId).HasColumnName("user_file_id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("now()")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("created_at");
            entity.Property(e => e.Extension)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("extension");
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasColumnType("character varying")
                .HasColumnName("file_path");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("updated_at");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.UserFiles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("userFile_user_key");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}