// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class RoleMenuMapping
{
    public int RoleMenuMappingId { get; set; }

    public int RoleId { get; set; }

    public int MenuId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool View { get; set; }

    public bool Edit { get; set; }

    public bool Create { get; set; }

    public bool Delete { get; set; }

    public virtual Menu Menu { get; set; }

    public virtual Role Role { get; set; }
}