// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class ShiftType
{
    public int ShiftTypeId { get; set; }

    public string Type { get; set; }

    public bool IsActive { get; set; }

    public TimeOnly? ShiftStartAt { get; set; }

    public TimeOnly? ShiftEndAt { get; set; }

    public int ShiftHours { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}