// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class UncropEmployeeFile
{
    public int UncropEmployeeFileId { get; set; }

    public int CropPictureId { get; set; }

    public string FilePath { get; set; }

    public string Extension { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual EmployeeFile CropPicture { get; set; }
}