// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PPFAttendanceApi.Models;

public partial class User
{
    public int UserId { get; set; }

    public string UserEmail { get; set; }

    public string UserPassword { get; set; }

    public string UserName { get; set; }

    public int RoleId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<AttendanceLog> AttendanceLogs { get; set; } = new List<AttendanceLog>();

    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();

    public virtual ICollection<DeviceSession> DeviceSessions { get; set; } = new List<DeviceSession>();

    public virtual ICollection<EmpUserBranchMapping> EmpUserBranchMappings { get; set; } = new List<EmpUserBranchMapping>();

    public virtual ICollection<EmpUserDepartmentMapping> EmpUserDepartmentMappings { get; set; } = new List<EmpUserDepartmentMapping>();

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    public virtual Role Role { get; set; }

    public virtual ICollection<UserFile> UserFiles { get; set; } = new List<UserFile>();
}